app:
  rss:
    # Период(в секундах) парсинга RSS с Youtube
    parseTimeout: 10

  schedule:
    # Настройка планировщика времени, каждый (день - day, неделю - week),
    every: week
    # Конкретный день недели, если параметр "every" равен "week" числом (1 - понедельник, 7 - воскресенье)
    day: 5
    # Конкретное время в 24 часовом формате
    time: "23:34"

  # Формат собственного поста
  customPost:
    # Текст сообщения, если нет, то оставить ""
    message: ""
    # Список файлов на диске, в той же директории, что и файл конфига. Передавать через запятую, без пробела
    files: image.jpg,image2.gif

services:
  youtube:
    # ID Youtube канала
    channelId: UC7d3fs1_WSbc6zCSDn9OhKO

  telegram:
    # Телеграм токен
    token: token
    # Название телеграм канала (знак @ обязателен, желательно указывать значение в кавычках "")
    channelId: "@somechannel"
    # Текст заголовка поста в телеграм
    postTitle: title

  vkontakte:
    # Токен доступа пользовательского приложения Вконтакте с правами доступа "wall"
    token: token
    # Идентификатор группы Вконтакте
    groupId: 23264234
    # Текст заголовка поста во Вконтакте
    postTitle: title
